# Artificial neural network

In [1]:
import numpy as np

In [2]:
#assign input values 

In [4]:
input_value = np.array([[0,0],[0,1],[1,1],[1,0]])
input_value.shape
input_value

array([[0, 0],
       [0, 1],
       [1, 1],
       [1, 0]])

In [5]:
#assign output values

In [6]:
output =np.array([0,1,1,0])
output= output.reshape(4,1)
output.shape

(4, 1)

In [7]:
#assign weights

In [8]:
weights=np.array([[0.1],[0.2]])
weights

array([[0.1],
       [0.2]])

In [9]:
#add bias

In [10]:
bias =0.3

In [11]:
#activation function

In [13]:
def sigmoid_func(x):
    return 1/(1+np.exp(-x))

In [15]:
# derivative of sigmoid function

In [16]:
def der(x):
    return sigmoid_func(x)*(1-sigmoid_func(x))

In [17]:
#updating weights

In [21]:
for epochs in range(10000):
    input_arr = input_value
    
    weighted_sum=np.dot(input_arr,weights)+bias
    first_output=sigmoid_func(weighted_sum)
    
    error=first_output-output
    total_error=np.square(np.subtract(first_output,output)).mean()
    #print(total_error)
    
    first_der=error
    second_der=der(first_output)
    derivative= first_der*second_der
    
    t_input=input_value.T
    final_derivative=np.dot(t_input,derivative)
    
    
    #update weights
    weights=weights- 0.05 *final_derivative
    
    #update bias
    
    for i in derivative:
        bias = bias - 0.05 * i
        
print(weights)
print(bias)

[[-0.41953547]
 [ 8.98887811]]
[-4.19706344]


In [24]:
#predictions

pred=np.array([1,0])

result =np.dot(pred,weights)+bias
res=sigmoid_func(result)
print(res)

[0.00978958]
